### PR TITLE
[WIP] [NÃO DA MERGE] HOMESTUCK : ALCHEMY PASS

### PR DESCRIPTION
**Pull request by taticalSniper**
literalmente eu cara

### CODE REVIEW

**Comment by thuxtk** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

**Comment by taticalSniper** [comment]
eu cara

**Comment by taticalSniper** [comment]
<@270895166800265216> da merge aqui

**Comment by taticalSniper** [comment]
vai caralho

**Comment by taticalSniper** [comment]
@thuxtk

**Comment by taticalSniper** [comment]
eis que o arrombado da merge

**Pull request merged**
